#!/usr/bin/env node
// Turns data/spawns.json + data/weather-dates.json into
// api/seeds/swsh-weather.sql: UPDATE statements that annotate Sword/Shield
// location entries with the weather a pokemon needs and the console date
// that forces that weather ("date skip").
//
//   'Giant''s Mirror'  ->  'Giant''s Mirror — Thunderstorm (set date: November 1st) / Overcast (set date: March 1st)'
//
// Only weather-restricted spawns are annotated: anything in an area's
// All Weather section (or listed under every weather) is left alone.
// Runs after data.sql + za.sql in `make db:seed`, so it's idempotent as part
// of that pipeline.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = process.argv[2] || 'api/seeds/swsh-weather.sql';

const spawns = JSON.parse(await readFile(join(ROOT, 'data', 'spawns.json'), 'utf8'));
const dates = JSON.parse(await readFile(join(ROOT, 'data', 'weather-dates.json'), 'utf8'));

const WEATHER_LABELS = {
  normalweather: 'Normal Weather',
  overcast: 'Overcast',
  raining: 'Raining',
  thunderstorm: 'Thunderstorm',
  snowing: 'Snowing',
  snowstorm: 'Snowstorm',
  sandstorm: 'Sandstorm',
  intensesun: 'Intense Sun',
  fog: 'Fog',
};
const ALL_WEATHERS = Object.keys(WEATHER_LABELS);

// Region determines which console date forces a given weather there.
const IOA_AREAS = new Set([
  'Fields of Honor', 'Soothing Wetlands', 'Forest of Focus', 'Challenge Beach',
  "Brawlers' Cave", 'Challenge Road', 'Courageous Cavern', 'Loop Lagoon',
  'Training Lowlands', 'Warm-Up Tunnel', 'Potbottom Desert', 'Workout Sea',
  'Stepping-Stone Sea', 'Insular Sea', 'Honeycalm Sea', 'Honeycalm Island',
]);
const CT_AREAS = new Set([
  'Slippery Slope', 'Frostpoint Field', "Giant's Bed", 'Old Cemetery',
  'Snowslide Slope', 'Tunnel to the Top', 'Path to the Peak', 'Crown Shrine',
  "Giant's Foot", 'Roaring-Sea Caves', 'Frigid Sea', 'Three-Point Pass',
  'Ballimere Lake', 'Lakeside Cave', 'Dyna Tree Hill', 'Freezington',
]);
const regionOf = (area) => (IOA_AREAS.has(area) ? 'ioa' : CT_AREAS.has(area) ? 'ct' : 'wild');

const GAME_IDS = {
  sword: ['sword', 'sword_expansion_pass'],
  shield: ['shield', 'shield_expansion_pass'],
};

const lit = (value) => `'${String(value).replace(/'/g, "''")}'`;

const lines = [
  '-- Generated by tools/swsh-weather/generate-sql.mjs — do not edit by hand.',
  '-- Annotates Sword/Shield locations with required weather + date skip.',
  'BEGIN;',
];

const regions = {};
let statements = 0;
for (const [area, byWeather] of Object.entries(spawns)) {
  const region = regionOf(area);
  (regions[region] ||= []).push(area);

  for (const game of ['sword', 'shield']) {
    const always = new Set(byWeather.allweather?.[game] || []);

    // pokemon -> sorted list of weather anchors it appears under
    const weathersByPokemon = {};
    for (const anchor of ALL_WEATHERS) {
      for (const nationalId of byWeather[anchor]?.[game] || []) {
        if (always.has(nationalId)) continue;
        (weathersByPokemon[nationalId] ||= []).push(anchor);
      }
    }

    // group pokemon that share the same weather set into one UPDATE
    const byCombo = {};
    for (const [nationalId, weathers] of Object.entries(weathersByPokemon)) {
      if (weathers.length === ALL_WEATHERS.length) continue; // spawns in every weather
      (byCombo[weathers.join(',')] ||= []).push(nationalId);
    }

    for (const [combo, nationalIds] of Object.entries(byCombo)) {
      const annotation = combo.split(',').map((anchor) => {
        const label = WEATHER_LABELS[anchor];
        const date = dates[label]?.[region];
        return date ? `${label} (set date: ${date})` : label;
      }).join(' / ');

      lines.push(
        `UPDATE locations SET "values" = array_replace("values", ${lit(area)}, ${lit(`${area} — ${annotation}`)}) ` +
        `WHERE game_id IN (${GAME_IDS[game].map(lit).join(',')}) ` +
        `AND pokemon_id IN (SELECT id FROM pokemon WHERE national_id IN (${nationalIds.join(',')}));`
      );
      statements++;
    }
  }
}

lines.push('COMMIT;');

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join('\n'));
console.log(`wrote ${OUT} (${statements} updates)`);
for (const [region, areas] of Object.entries(regions)) {
  console.log(`  ${region}: ${areas.length} areas`);
}
