#!/usr/bin/env node
// Generates api/seeds/za.sql — Legends: Z-A support on top of the scraped
// dataset (api/seeds/data.sql). Adds:
//
//   game_families: legends_z_a, legends_z_a_mega_dimension
//   games:         Legends: Z-A, Legends: Z-A (Mega Dimension)
//   dex_types:     101 Regional  (legends_z_a, Lumiose dex)
//                  102 Lumiose   (mega dimension family)
//                  103 Hyperspace (mega dimension family)
//   dex_types_pokemon: memberships mapping dex numbers to the existing
//                  shared pokemon rows (all Z-A species already exist as
//                  base-form rows; no new pokemon rows are needed)
//
// Dex type ids start at 101 to stay clear of upstream's ids if the seed is
// ever regenerated from a newer live dataset.
//
// Inputs: tools/za/data/{lumiose,hyperspace}.json (from fetch-serebii.mjs)
// and the scrape cache (for national_id -> pokemon row id mapping).
//
// Usage:
//   node tools/za/generate-za-sql.mjs [--cache tools/scrape/cache] [--out api/seeds/za.sql]

import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
function flag (name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? fallback : args[i + 1];
}

const CACHE = flag('cache', 'tools/scrape/cache');
const OUT = flag('out', 'api/seeds/za.sql');
const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), 'data');

const lumiose = JSON.parse(await readFile(join(DATA_DIR, 'lumiose.json'), 'utf8'));
const hyperspace = JSON.parse(await readFile(join(DATA_DIR, 'hyperspace.json'), 'utf8'));
const locationData = JSON.parse(await readFile(join(DATA_DIR, 'locations.json'), 'utf8').catch(() => '{}'));

// Map national_id -> base-form pokemon row id. Some species have duplicate
// rows in the upstream dataset (one per game family that re-lists them), and
// only one set carries coherent evolution edges: the rows referenced by the
// HOME "Full National" dex. Use that mapping first, and fall back to a cache
// scan only for species the national dex somehow lacks.
const rowByNationalId = {};
for (const file of (await readdir(join(CACHE, 'pokemon'))).filter((f) => f.endsWith('.json'))) {
  const p = JSON.parse(await readFile(join(CACHE, 'pokemon', file), 'utf8'));
  if (p.form === null && !(p.national_id in rowByNationalId)) rowByNationalId[p.national_id] = p.id;
}
const dexTypesInCache = JSON.parse(await readFile(join(CACHE, 'dex-types.json'), 'utf8'));
const nationalDexType = dexTypesInCache
  .filter((dt) => dt.game_family_id === 'home' && !dt.base_dex_type_id)
  .sort((a, b) => a.order - b.order)[0];
if (nationalDexType) {
  const captures = JSON.parse(await readFile(join(CACHE, 'captures', `${nationalDexType.id}.json`), 'utf8'));
  for (const capture of captures) {
    if (capture.pokemon.form === null) rowByNationalId[capture.pokemon.national_id] = capture.pokemon.id;
  }
}

const FAMILY_BASE = 'legends_z_a';
const FAMILY_DLC = 'legends_z_a_mega_dimension';
const DEX_TYPES = [
  { id: 101, name: 'Regional', family: FAMILY_BASE, order: 0, entries: lumiose },
  { id: 102, name: 'Lumiose', family: FAMILY_DLC, order: 0, entries: lumiose },
  { id: 103, name: 'Hyperspace', family: FAMILY_DLC, order: 1, entries: hyperspace },
];

const lines = [
  '-- Generated by tools/za/generate-za-sql.mjs — do not edit by hand.',
  '-- Legends: Z-A dexes built from Serebii listings (tools/za/data/).',
  'BEGIN;',
  // Idempotent: clear any previous Z-A rows first.
  `DELETE FROM dex_types_pokemon WHERE dex_type_id IN (${DEX_TYPES.map((dt) => dt.id).join(',')});`,
  `DELETE FROM dexes WHERE dex_type_id IN (${DEX_TYPES.map((dt) => dt.id).join(',')});`,
  `DELETE FROM dex_types WHERE id IN (${DEX_TYPES.map((dt) => dt.id).join(',')});`,
  `DELETE FROM games WHERE game_family_id IN ('${FAMILY_BASE}', '${FAMILY_DLC}');`,
  `DELETE FROM game_families WHERE id IN ('${FAMILY_BASE}', '${FAMILY_DLC}');`,

  // Newer upstream families (PLA, S/V) leave the legacy total/support fields
  // zeroed, so these do too. Orders continue after S/V expansion (23/41);
  // HOME sits at 9999.
  'INSERT INTO game_families (id, generation, regional_total, national_total, regional_support, national_support, "order", published) VALUES',
  `('${FAMILY_BASE}', 9, 0, 0, FALSE, FALSE, 24, TRUE),`,
  `('${FAMILY_DLC}', 9, 0, 0, FALSE, FALSE, 25, TRUE);`,

  'INSERT INTO games (id, name, game_family_id, "order") VALUES',
  `('legends_z_a', 'Legends: Z-A', '${FAMILY_BASE}', 42),`,
  `('legends_z_a_mega_dimension', 'Legends: Z-A (Mega Dimension)', '${FAMILY_DLC}', 43);`,

  'INSERT INTO dex_types (id, name, game_family_id, "order", tags) VALUES',
  DEX_TYPES.map((dt) => `(${dt.id}, '${dt.name}', '${dt.family}', ${dt.order}, ARRAY['regional']::text[])`).join(',\n') + ';',
];

const missing = [];
for (const dt of DEX_TYPES) {
  const rows = dt.entries.map((e, i) => {
    const pokemonId = rowByNationalId[e.national_id];
    if (!pokemonId) missing.push(`${dt.name} #${e.dex_number} ${e.name} (national ${e.national_id})`);
    return `(${dt.id}, ${pokemonId}, NULL, ${i}, ${e.dex_number})`;
  });
  lines.push(`INSERT INTO dex_types_pokemon (dex_type_id, pokemon_id, box, "order", dex_number) VALUES\n${rows.join(',\n')};`);
}
if (missing.length > 0) {
  throw new Error(`no base-form pokemon row for:\n  ${missing.join('\n  ')}`);
}

// Locations, scraped from Serebii's per-species pages (fetch-locations.mjs).
// The base game gets the "Legends: Z-A" rows; the Mega Dimension game gets
// base + Hyperspace rows merged, since the DLC contains the base game. The
// DELETE FROM games above cascades away any previous rows.
const lit = (v) => `'${String(v).replace(/'/g, "''")}'`;
const arrayLit = (values) => `ARRAY[${values.map(lit).join(',')}]::text[]`;

const locationRows = [];
const dlcSpecies = new Set([...lumiose, ...hyperspace].map((e) => e.national_id));
for (const e of lumiose) {
  const values = locationData[e.national_id]?.za;
  if (values?.length) locationRows.push(`('legends_z_a', ${rowByNationalId[e.national_id]}, ${lit(values.join('; '))}, ${arrayLit(values)})`);
}
for (const nationalId of dlcSpecies) {
  const za = locationData[nationalId]?.za || [];
  const md = locationData[nationalId]?.md || [];
  const values = [...za, ...md];
  if (values.length) locationRows.push(`('legends_z_a_mega_dimension', ${rowByNationalId[nationalId]}, ${lit(values.join('; '))}, ${arrayLit(values)})`);
}
if (locationRows.length > 0) {
  lines.push(`INSERT INTO locations (game_id, pokemon_id, value, "values") VALUES\n${locationRows.join(',\n')};`);
}

lines.push("SELECT setval('dex_types_id_seq', GREATEST((SELECT MAX(id) FROM dex_types), 103));");
lines.push('COMMIT;');

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join('\n\n'));
console.log(`wrote ${OUT}`);
console.log(`  Regional (Lumiose):   ${lumiose.length} pokemon`);
console.log(`  Hyperspace:           ${hyperspace.length} pokemon`);
